## Numpy Library Exercises

In [ ]:
import numpy as np

**1.** Given a random array, change the sign of elements whose values ​​are between 3 and 8

In [ ]:
arr = np.array([-5,4,2,6,-8])
res = np.where((arr >= 3) & (arr<=8), arr*(-1), arr)
print(res)

[-5 -4  2 -6 -8]


**2.** Replace the maximum element of a random array with 0

In [ ]:
arr = np.array([-3,5,2,19])
arr[np.argmax(arr)] = 0
print(arr)

[-3  5  2  0]


**3.** Construct the direct product of arrays (all combinations with each element). A two-dimensional array is provided as input.

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
r0, r1 = np.meshgrid(arr[0], arr[1])
res = np.stack([r0, r1], axis=-1)
print(res)

[[[1 4]
  [2 4]
  [3 4]]

 [[1 5]
  [2 5]
  [3 5]]

 [[1 6]
  [2 6]
  [3 6]]]


**4.** Given two arrays, A (8x3) and B (2x2), find rows in A that contain elements from each row in B, regardless of the order of the elements in B.

In [ ]:
A = np.array([
    [1, 5, 9],
    [2, 3, 8],
    [4, 7, 1],
    [0, 6, 2],
    [5, 8, 3],
    [9, 1, 4],
    [2, 7, 6],
    [3, 5, 0]
])

B = np.array([
    [1, 2],
    [3, 4]
])

B0 = np.isin(A, B[0]).any(axis=1)
B1 = np.isin(A,B[1]).any(axis=1)
result = A[B0 & B1]
print(result)

[[2 3 8]
 [4 7 1]
 [9 1 4]]


**5.** Given a 10x3 matrix, find rows of unequal values ​​(for example, the row [2,2,3] remains, the row [3,3,3] is deleted)

In [ ]:
arr = np.array([
    [1,2,2],
    [5,5,5],
    [0,5,5],
    [4,4,2],
    [0,0,0],
    [1,2,2],
    [5,5,5],
    [0,5,5],
    [4,4,2],
    [0,0,0]
])

result = arr[np.array([len(np.unique(row)) > 1 for row in arr])]
print(result)

[[1 2 2]
 [0 5 5]
 [4 4 2]
 [1 2 2]
 [0 5 5]
 [4 4 2]]


**6.** Given a two-dimensional array, remove the rows that are repeated.

In [ ]:
arr = np.array([
    [1,2,2],
    [5,5,5],
    [0,5,5],
    [4,4,2],
    [0,0,0],
    [1,2,2],
    [5,5,5],
    [0,5,5],
    [4,4,2],
    [0,0,0]
])

result = np.unique(arr, axis=0)
print(result)

[[0 0 0]
 [0 5 5]
 [1 2 2]
 [4 4 2]
 [5 5 5]]


______
______

For each of the following problems (1-5) you need to provide 2 implementations – one without using numpy (Consider that where the input or output should be a numpy array, there will simply be lists), and the second one is fully vectorized using numpy (without using Python loops/map/list comprehension).


__Note 1.__ It can be assumed that all specified objects are non-empty (for example, in __task 1__ there are non-zero elements on the diagonal of the matrix).

__Note 2.__ For most tasks, the solution takes no more than 1-2 lines.

___

* __Task 1__: Calculate the product of nonzero elements on the diagonal of a rectangular matrix.  
 For example, for X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) answer is 3.

In [ ]:
def product_diagonal_python(X):
    rows = len(X)
    cols = len(X[0])

    result = 1
    has_nonzero = False

    for i in range(min(rows, cols)):
        if X[i][i] != 0:
            result *= X[i][i]
            has_nonzero = True

    return result if has_nonzero else 0

def product_diagonal_numpy(X):
    diag = np.diag(X)
    return np.prod(diag[diag != 0]) if np.any(diag != 0) else 0

X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
X_list = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]

print(f"np: {product_diagonal_numpy(X)}")
print(f"python: {product_diagonal_python(X_list)}")

np: 3
python: 3


* __Task 2__: Two vectors x and y are given. Check if they define the same multiset.  
  For example, for x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) answer is True.

In [ ]:
from collections import Counter

X_list = [1,2,2,4]
Y_list = [4,2,1,2]
X = np.array([1,2,2,4])
Y = np.array([4,2,1,2])

def same_multiset_python(X,Y):
  return Counter(X) == Counter(Y)

def same_multiset_numpy(x, y):
    vals_x, counts_x = np.unique(x, return_counts=True)
    vals_y, counts_y = np.unique(y, return_counts=True)

    return np.array_equal(vals_x, vals_y) and np.array_equal(counts_x, counts_y)

print(same_multiset_python(X_list, Y_list))
print(same_multiset_numpy(X,Y))

True
True


* __Task 3__: Find the maximum element in the vector x among the elements preceded by zero.
 For example, for x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) answer is 5.

In [ ]:
def max_after_zero_python(X):
    candidates = [X[i + 1] for i in range(len(X) - 1) if X[i] == 0]
    return max(candidates) if candidates else None

def max_after_zero_numpy(X):
    A = X[:-1]
    B = X[1:]

    candidates = B[A == 0]

    return np.max(candidates) if len(candidates) > 0 else None

X = np.array([6,2,0,3,0,0,5,7,0])
X_list = [6,2,0,3,0,0,5,7,0]

print(max_after_zero_numpy(X))
print(max_after_zero_python(X_list))

5
5


* __Task 4__: Implement run-length encoding. For some vector x, it is necessary to return a tuple of two vectors of the same length. The first one contains numbers and the second one contains how many times they need to be repeated.  
 For example, for x = np.array([2, 2, 2, 3, 3, 3, 5]) answer is (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [ ]:
def rle_python(x):
    if len(x) == 0:
        return ([], [])

    values = []
    counts = []

    current_val = x[0]
    count = 1

    for i in range(1, len(x)):
        if x[i] == current_val:
            count += 1
        else:
            values.append(current_val)
            counts.append(count)
            current_val = x[i]
            count = 1

    values.append(current_val)
    counts.append(count)

    return (values, counts)

def rle_numpy(x):
    if len(x) == 0:
        return np.array([]), np.array([])

    changes = np.where(x[1:] != x[:-1])[0] + 1
    idxs = np.concatenate(([0], changes, [len(x)]))

    values = x[idxs[:-1]]
    counts = np.diff(idxs)

    return values, counts

x = np.array([2, 2, 2, 3, 3, 3, 5])
x_list = [2, 2, 2, 3, 3, 3, 5]
print(rle_numpy(x))
print(rle_python(x_list))

(array([2, 3, 5]), array([3, 3, 1]))
([2, 3, 5], [3, 3, 1])


* __Task 5__: Two samples of objects are given - X and Y. Calculate the matrix of Euclidean distances between objects. Compare with function scipy.spatial.distance.cdist by operating speed.

In [ ]:
from scipy.spatial.distance import cdist
import time

def cdist_python(X, Y):
    M = X.shape[0]
    N = Y.shape[0]
    distances = np.zeros((M, N))

    for i in range(M):
        for j in range(N):
            distances[i, j] = np.sqrt(np.sum((X[i] - Y[j]) ** 2))
    return distances

def cdist_numpy(X, Y):
    diff = X[:, np.newaxis, :] - Y
    return np.sqrt(np.sum(diff**2, axis=2))

X = np.random.rand(200, 10)
Y = np.random.rand(300, 10)

t0 = time.time()
res_py = cdist_python(X, Y)
time_py = time.time() - t0

t0 = time.time()
res_np = cdist_numpy(X, Y)
time_np = time.time() - t0

t0 = time.time()
res_scipy = cdist(X, Y, metric="euclidean")
time_scipy = time.time() - t0

print(f"Python: {time_py:.4f} s")
print(f"Numpy: {time_np:.4f} s")
print(f"SciPy: {time_scipy:.5f} s")

Python: 0.3102 s
Numpy: 0.0053 s
SciPy: 0.00047 s


_______
________

* #### __Task 6__: CrunchieMunchies __*__

You work in the marketing department of a food company called MyCrunch, which is developing a new type of delicious, healthy cereal called **CrunchieMunchies**.

You want to show consumers how healthy your cereal is compared to other leading brands, so you've compiled nutrition data from several different competitors.

Your task is to use Numpy calculations to analyze this data and prove that your **СrunchieMunchies** - the healthiest choice for consumers.


In [ ]:
import numpy as np

1. View the cereal.csv file. This file contains calorie counts for various brands of cereal. Download the data from the file and save it as calorie_stats.

In [ ]:
calorie_stats = np.loadtxt("cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. One serving of CrunchieMunchies contains 60 calories. How much higher is the average calorie count of your competitors?

Store the answer in the variable average_calories and print the variable in the terminal

In [ ]:
average_calories = np.mean(calorie_stats)
print(average_calories)
print(f"diff: {average_calories - 60}")

106.88311688311688
diff: 46.883116883116884


3. Does the average calorie count accurately reflect the distribution of the data set? Let's sort the data and see.

Sort the data and store the result in the calorie_stats_sorted variable. Print the sorted information.

In [ ]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. It looks like most values ​​are above the mean. Let's see if the median is the most accurate measure of the data set.

Calculate the median of the data set and save your answer in median_calories. Print the median so you can see how it compares to the mean.

In [ ]:
median_calories = np.median(calorie_stats)

print(median_calories)

110.0


5. While the median shows that at least half of our values ​​are over 100 calories, it would be more impressive to show that a significant portion of the competitors have higher calorie counts than CrunchieMunchies.

Calculate various percentiles and print them until you find the lowest percentile that exceeds 60 calories. Store this value in the nth_percentile variable.

In [ ]:
print(np.percentile(calorie_stats, 3))
print(np.percentile(calorie_stats, 4))

nth_percentile = 4

55.599999999999994
70.0


6. While the percentile shows us that most competitors have much higher calorie counts, it's an awkward concept to use in marketing materials.

Instead, let's calculate the percentage of cereals that contain more than 60 calories per serving. Save your answer in the more_calories variable and print it.

In [ ]:
more_calories = np.mean(calorie_stats > 60) * 100
print(more_calories)

96.1038961038961


7. This is a really high percentage. This will be very useful as we promote CrunchieMunchies. But one question is: how big are the differences in the dataset? Can we generalize that most cereals contain around 100 calories or is the range even wider?

Calculate the magnitude of the deviation by finding the standard deviation. Save your answer in calorie_std and print it on the terminal. How can we incorporate this value into our analysis?

In [ ]:
calorie_std = np.std(calorie_stats)
print(calorie_std)

19.35718533390827


8. Please write a short paragraph outlining your findings and how you believe this data can be used to Mycrunch's advantage in marketing CrunchieMunchies.

In [ ]:
#CrunchieMunchies have lower calories than 96.1% of the others.
#Average calories per serving is almost 107 therefore almost 47 more calories per serving than CrunchieMunchies.
#Standard deviation is around 19.4 that means most of other products have calories per serving in range 88-126 which is visibly higher than 60